### PR TITLE
Automatic calculation of XP costs #114

### PR DESCRIPTION
**Pull request by FilippoPolo**
Implementing #114.

- Adds checkboxes in the Advances tab to specify that a given talent or skill comes from character creation (and is therefore free).
- Adds a field for "Other" XP expenses to the total costs; this is directly editable and can be used for e.g. elite advances or such.
- Adds a config setting to enable automatic calculation of XP costs. If the setting is not enabled, the following changes do not take place.
- If the setting is enabled, all cost boxes are disabled (except for psychic powers and "Other") and the system automatically calculates XP costs for advances.
- The sheet must correctly include Aptitudes. They can either come from the compendium, or be added by hand (in this case, they must be spelled correctly).
- The user must correctly fill in the Aptitudes and Tier fields for talents (in the case of Aptitudes, they should be spelled correctly and separated by a comma). This could be avoided by using a talent compendium.
- The user must fill in psychic powers costs normally.

Please note that I didn't lint this, because master isn't linted at the moment and I don't want to add a whole lot of unrelated diffs.

### CODE REVIEW

**Comment by Vendare** [comment]
Integrated the older PRs please resolve the resulting conflicts on your side

**Comment by FilippoPolo** [comment]
I've fixed the conflicts. I'm not sure why github still says there are conflicts.

**Comment by Vendare** [comment]
You need to also add migration. Old Actors don't have the new apitudes in their characteristics so your auto calcualtion doesn't work on old actors only on new ones.

**Comment by FilippoPolo** [comment]
I just did the following test:

1. Installed dark-heresy without auto-calc-costs.
2. Created a new world, with an actor in it. Added some upgrades with wrong XP costs to the actor.
3. Shut down the world.
4. Overwrote dark-heresy installation with auto-calc-costs.
5. Restarted the world.
6. Enabled the "Calculate XP Costs" flag in the settings.
7. Added another upgrade to the actor.

The result I observe is that all XP costs for the actor are correctly recalculated.

I think that Foundry is seeing that template.json has new fields, and is adding them to the data model with their default values. Since those values are immutable anyway, this is sufficient for migration. Er, at least I think that's what's going on; I've only started doing Foundry development for a short while. ^_^'

Did you somehow end up in a situation where the auto-calc was enabled, but didn't work?

Or do you think that all actors should get recalculated when the "Calculate XP Costs" flag is enabled in the settings? Currently, you have to make a change to the actor to trigger recalculation. I'm slightly reluctant to changing that, because recalc cannot be undone, and one could click the checkbox by mistake...

**Comment by Vendare** [comment]
May have been a caching problem on my end

**Pull request merged**
